# -----------------------------------------------------
# Window rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# -----------------------------------------------------

windowrule = opacity 0.92 0.92, match:class Alacritty
