---
name: Trigger downstream workflow

on:
  workflow_dispatch:

env:
  DOWNSTREAM_REPO: dotfiles.nix
  WORKFLOW_FILE: sync-upstream.yml
  REF: ${{ github.event.repository.default_branch }}

jobs:
  dispatch-downstream-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Extract sync target from repo name
        shell: bash
        run: echo "TARGET=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" | sed 's/dot-//' >> $GITHUB_OUTPUT
        id: sync_target

      - name: Trigger
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ env.DOWNSTREAM_REPO }}
          github_token: ${{ secrets.ACCESS_TOKEN }}
          github_user: ${{ github.repository_owner }}
          workflow_file_name: ${{ env.WORKFLOW_FILE }}
          ref: ${{ env.REF }}
          client_payload: '{"target":"${{ steps.sync_target.outputs.TARGET }}"}'
          trigger_workflow: true
          propagate_failure: false
          wait_interval: 60
          wait_workflow: true
